name: Run Tests
on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Setup Node ENV
        uses: actions/setup-node@v4

      - name: Build Docker instance
        run: npm run setup-db

      - name: Get Docker IP
        id: docker-ip
        run: echo IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aqf 'name=psql')) >> "$GITHUB_OUTPUT"

      - name: Install Packages
        run: npm ci

      - name: Run Tests
        run: echo "$DATABASE_URL"
        env:
          DATABASE_URL: 'postgresql://root:root@${{ steps.docker-ip.outputs.IP }}:5432/clowder'
